### ISSUE TITLE
GeMoMa died with error running AF

### ISSUE THREAD

**Issue by kdarragh1994** [molevol-ub/bitacora#11]
Hi,

I am running with GeMoMa version 1.9 and java version 11.0. The error message is this:
Exception in thread "main" java.lang.NullPointerException
	at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:690)
	at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:603)
	at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:94)
	at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
	at projects.gemoma.GeMoMa.main(GeMoMa.java:399)

A few things to add. The example file runs without error which I assume means this is an issue with my input data. 
The gff3 file is a braker.gtf output on which I ran fix_gtf_ids.py and then  agat to check for formatting issues and also used the gff2fasta_v3.pl to generate my protein data. 
I have tried this with various versions of the gff3 file. First, I tried running agat directly on the braker.gtf output, then I tried with the fix_gtf_ids.py before agat. And finally I also tried sorting the gff3 file with igvtools. I'm confused because I have used bitacora following braker before and have not run into these issues.

Any idea what could be causing this?

Thank you,
Kathy

**Comment by kdarragh1994** [comment]
Thanks so much - it was in fact an issue with the genome fasta file! Thanks for pointing out it wasn't the gff3 file.

**Comment by kdarragh1994** [comment]
Hello again,

I'm coming across this exact same issue with a different genome. https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_004115045.4/

I downloaded it from here on NCBI and am getting the same error. As before, I can run the example so I know this isn't an issue with installation, I also also use bitacora regularly without issue. Any ideas why this genome might cause this?
I tried checking the formatting, removing spaces, running a script called  fasta o matic to double check the formatting. I cannot work out what could possibly be going wrong. 

My exact error:
Exception in thread "main" java.lang.NullPointerException
	at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:690)
	at projects.gemoma.AnnotationFinalizer.run(AnnotationFinalizer.java:603)
	at projects.gemoma.GeMoMaModule.run(GeMoMaModule.java:94)
	at de.jstacs.tools.ui.cli.CLI.run(CLI.java:426)
	at projects.gemoma.GeMoMa.main(GeMoMa.java:399)

Thank you for the help!!

**Comment by Vizueta** [comment]
Hi, 

I recommend that you check the genome to see if there is any issue, mask any base that is not "A C T G" as an N, and rename the identifiers so they only contain A-Z characters so GeMoMa does not complain and fails running. 

Best,
Joel

**Comment by daisysotero** [comment]
Hi, 
I also encountered the following error when running BITACORA in genome mode:


`-----------------` Starting PF01397 Genomic Gene Identification and Annotation
Doing PF01397 tblastn
Parsing PF01397 tblastn
Using GeMoMa to predict novel genes
ERROR in /home/coffea/daisy/pangenoma_tps/bitacora_v1.4/bitacora/Scripts/runanalysis_2ndround_genomic_nogff_gemoma: GeMoMa died with error running AF`


I created a genome .fna file containing a single chromosome.
When I input 50% of this chromosome, the pipeline works correctly. When I input the entire chromosome, it fails with the error above. The genome contains only A, C, T, G and masked regions (N or lowercase actg). I am running the pipeline in genome mode using runBITACORA_genome_mode.sh.

Could this be related to chromosome length? Any guidance on how to resolve this would be greatly appreciated.
